#-----------------------------#
#    General configuration    #
#-----------------------------#

# Version number
version: 0.1.{build}-{branch}

# Branches to build
branches:
  only:
    - master
    - develop
    - feature/appveyor_integration

# Maximum number of concurrent jobs
max_jobs: 1

#-----------------------------#
#  Environment configuration  #
#-----------------------------#

environment:
  matrix:
    - compiler: msys2
      ARCH: x64
      MSYS2_ARCH: x86_64
      MSYS2_DIR: msys64
      MSYSTEM: MINGW64
    - compiler: msys2
      ARCH: x86
      MSYS2_ARCH: i686
      MSYS2_DIR: msys64
      MSYSTEM: MINGW32

# Clone directory
clone_folder: c:\vcv-link-build\vcv-link

# Scripts that are called at very beginning, before repo cloning
before_build:
  - cd c:\vcv-link-build
  - git clone --recursive https://github.com/VCVRack/Rack.git vcv-rack
  
install:
  - PATH C:\%MSYS2_DIR%\%MSYSTEM%\bin;C:\%MSYS2_DIR%\usr\bin;%PATH%
  - bash -lc "pacman -S git make tar unzip mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake"
  #- cinst make --yes

#-----------------------------#
#     Build configuration     #
#-----------------------------#

# Build platform and configuration
platform: Any CPU
configuration: Release

build_script:
  - cd c:\vcv-link-build\vcv-link
  - make
